name: Publish Package to npmjs
on:
  release:
    types: [created]
jobs:
  build:
    env:
      NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      # Setup .npmrc file to publish to npm
      - uses: actions/setup-node@v3
        with:
          node-version: '18.x'
          registry-url: 'https://registry.npmjs.org'
      - run: npm install
      - run: npm run test
      - run: npm run build
      - name: Update version
        run: npm version ${{ github.event.release.tag_name }}
      - run: npm publish
